//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanAPoundCreditCheckService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public int ApplicationID { get; set; }
        public int ApplicantID { get; set; }
        public Nullable<double> DepositOffered { get; set; }
        public Nullable<double> PropertyValue { get; set; }
        public Nullable<int> Term { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
