//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanAPoundCreditCheckService.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class ApplicantCreditCheckScore
    {
        public int CreditCheckTransactionID { get; set; }
        public Nullable<int> ApplicantID { get; set; }
        public Nullable<int> CreditCheckProviderID { get; set; }
        public Nullable<int> CreditScore { get; set; }
    }
}
