//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanAPoundCreditCheckService.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class Applicant
    {
        public int ApplicantID { get; set; }

        [DisplayName("First Name")]
        public string ApplicantFirstName { get; set; }

        [DisplayName("Last Name")]
        public string ApplicantLastName { get; set; }

        [DisplayName("Annual Salary")]
        public double AnnualSalary { get; set; }

        [DisplayName("NI Number")]
        public string NI_Number { get; set; }

        [DisplayName("Address")]
        public string Address { get; set; }

        [DisplayName("Email Address")]
        public string Email { get; set; }
    }
}
