//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanAPoundCreditCheckService.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LoanAPoundDataEntities : DbContext
    {
        public LoanAPoundDataEntities()
            : base("name=LoanAPoundDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Applicant> Applicants { get; set; }
        public DbSet<ApplicantCreditCheckScore> ApplicantCreditCheckScores { get; set; }
        public DbSet<Application> Applications { get; set; }
        public DbSet<CreditCheckProvider> CreditCheckProviders { get; set; }
        public DbSet<Loan> Loans { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<User> Users { get; set; }
    }
}
