//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanAPoundCreditCheckService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loan
    {
        public int LoanID { get; set; }
        public string LoanProvider { get; set; }
        public Nullable<int> Term { get; set; }
        public Nullable<double> BorrowingRate { get; set; }
        public Nullable<double> MaxLoanAmount { get; set; }
        public Nullable<int> LoanType { get; set; }
    }
}
